### ISSUE TITLE
Upgrade to TF 2.0

### ISSUE THREAD

**Issue by maxmstrmn** [wizard-kv/Self-Driving-Car#1]
This code can't be used with Tensorflow 2.0. Please upgrade it!

**Comment by kunwar-vikrant** [comment]
can you describe the issue you are facing?!

**Comment by maxmstrmn** [comment]
Yeah, if you Upgrade everything the code can't be run and executed.

**Comment by kunwar-vikrant** [comment]
if you provide me with the error logs...i can update the code accordingly!
